### ISSUE TITLE
Cannot read property 'removeMediaQueryListeners' of undefined - Live Updates

### ISSUE THREAD

**Issue by rafaelchiti** [chartist-js/chartist#106]
Hi!, wondering if someone ran into this issue.

Chartist does not support live updates on the data therefore you need to instantiate the chart each time you want to update it.

If you call `new Chart` twice in the same tick an error will be thrown due to some internals of the library.

A JSFiddle here. http://jsfiddle.net/gxxm02yj/

Basically what happens is that executing new Chart checks if the chart already exist in the DOM node and if so calls the internal `detach`. Detach will call `this.optionsProvider.removeMediaQueryListeners`. The problem is that chartist will initialize the this.optionsProvider property on a `setTimeout` therefore the second time you call the `new Chart` the property this.optionsProvider won't exist.

The reason why I'm doing a `new` twice in the same tick is because of some internals of how stuff is being managed in my app with React JS, I could get rid of that but still feels no right to me not being able to do so, does that make sense?

Thanks very much!

**Comment by gionkunz** [comment]
Hey there. You're actually spot on. The reason why chartist defers some of its initialization with a setTimeout into the event loop is actually due to a few reasons (first render is outside current callstack which allows user to add event listeners before the chart is drawn, this could also be achieved by removing rendering from constructor and make it explicit but this would break backwards compatibility but should maybe be considered for chartist 1.0).

This is a bug and should be fixed, even it's maybe a odd use-case to initialize a chart twice in the same call stack.

For now a quick fix would be to save the timeout ID from the setTimeout in the chart object `this.initializeTimeoutId = setTimeout...` https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/base.js#L95 and in the callback of the timeout https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/base.js#L113 we could set it to `null` again. Then in the check for `__chartist__` https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/base.js#L85  we would also need to check for the timeout id on the chart object and if it's not null cancel the timeout. If it's null proceed with the detach. Also the window.resize listener should go into the timeout to keep things simple.

I'm a bit under water with work so can't pick it up soon. I'd appreciate some inputs or a PR would be awesome!

Cheers
Gion

**Comment by tmcw** [comment]
Still running into this error within the context of [react-chartist](https://github.com/fraserxu/react-chartist).

**Comment by stefanvermaas** [comment]
Maybe because react-charist is using the 0.7.3 version of chartist? 

Edit: Updating react-chartist to the latest charist JS version didn't fix this me for.

**Comment by snide** [comment]
@stefanvermaas Did you happen to find a solution. Running into the same thing with react-chartist as well.

**Comment by stefanvermaas** [comment]
I'm afraid not. I dropped chartist and started using chartjs

**Comment by gionkunz** [comment]
Can someone give a clear reproducable case where this happens?

**Comment by snide** [comment]
@gionkunz @stefanvermaas So after talking with some of our react pros we figured out that this was due to passing the chart.data around as states in the `componentDidMount` function. Any state changes will force a rerender, which is why you get the error like above. Moving the data to `compomentWillMount` which is run before the render will avoid the issue. Still, you'd end up having it if you changes the state along the way.

@gionkunz I also just want to applaud your work here. I've worked on various charting libs over the years and this one is extremely well documented and configurable for a designer like myself to build fun, cool charts.

**Comment by gpbmike** [comment]
The key here is that you don't want to render the chart component multiple times back to back. Something like this could help too inside of your chart component (React). Assuming your data is coming into the component via props.

``` javascript
shouldComponentUpdate: function(nextProps) {
    return JSON.stringify(nextProps) !== JSON.stringify(this.props);
}
```

Now the component won't re-render every time the parent does if the data does not change.

If the data changes at such a rate that you still run into this error, then perhaps debouncing is the way to go.

**Comment by gionkunz** [comment]
I've also found a flaw in Chartist where the detach function tried to detach even when the scheduled async initialization has not fired yet. I've fixed this with 0dabf39 and refactored some code with 4b0a7b7. These will go into 0.8.3 this weekend.

**Comment by gionkunz** [comment]
If the react module was using detach then this will also fix some issues there I guess.
